### ISSUE TITLE
Sessions don't play well with futures and agents

### ISSUE THREAD

**Issue by robhanlon22** [aroemers/mount-lite#22]
I've been running into an issue where a library I use internally spawns a future which eventually calls back into my application code. Since futures are run on a thread pool initialized by Clojure, they lose the value of the inheritable thread local and are thus unable to tell which session they're associated with. It seems like a way to handle this would be to use a `binding` rather than a new Thread in `with-session`, and perhaps provide a function that could be used to convey the session to new threads.

**Comment by aroemers** [comment]
This is indeed a [documentend](https://cljdoc.org/d/functionalbytes/mount-lite/2.3.0/doc/troubleshooting#why-do-i-get-an-exception-or-a-value-from-a-different-session-when-i-access-a-state) known issue. A binding would have the same issue. The (unfinished) 3.x branch has a proper solution for this.
