### ISSUE TITLE
Support clj-kondo hooks for this project

### ISSUE THREAD

**Issue by D00mch** [aroemers/mount-lite#29]
To avoid diagnostics when working with LSP:
![image](https://user-images.githubusercontent.com/14236531/199926130-82b65611-5072-4ec5-bfcd-1b8d5469a47e.png)

**Comment by D00mch** [comment]
I could make a PR if you want.

**Comment by aroemers** [comment]
Great idea! A pull request is welcome of course.

**Comment by D00mch** [comment]
https://github.com/aroemers/mount-lite/pull/30

**Comment by aroemers** [comment]
Released in 2.3.0.
