### ISSUE TITLE
Exception while require: "No such var: parse/name-from-ns-decl"

### ISSUE THREAD

**Issue by aksenov** [aroemers/mount-lite#6]
Got exception while trying to require mount-lite.

Steps to reproduce problem:
```
lein new app mount-lite-test
add  [functionalbytes/mount-lite "0.9.4"] to project.clj
lein deps
lein repl
mntl.core=> (require '[mount.lite :as mount])
CompilerException java.lang.RuntimeException: No such var: parse/name-from-ns-decl, compiling:(mount/lite/graph.clj:15:29)
```

Working under Windows 10, if it's matter

**Comment by aroemers** [comment]
Hi @aksenov,

If I follow your steps, I don't get the issue you are having. I am on OS X, but I doubt that would matter. Are you using the `tools.namespace` library by any chance, either in your `project.clj` of `profiles.clj`? Mount-lite requires the latest version of that library (version 0.3.0-alpha3).

**Comment by aroemers** [comment]
@aksenov This might identify where you probably have a version conflict: 
```
lein with-profile +repl deps :tree
```

**Comment by aksenov** [comment]
Yep, it was dependency conflict with `tools.namespace` of old CIDER plugin (0.8.5) in global Lein settings. Now all works fine.

**Comment by aksenov** [comment]
Thanks for help and for useful library. I like your point of view on `mount `functionality. Keep it lite.

**Comment by aroemers** [comment]
Glad you like it, and thanks for reporting back. Have fun!
