### ISSUE TITLE
Not working with uberjar

### ISSUE THREAD

**Issue by aksenov** [aroemers/mount-lite#7]
Step to reproduce problem:
`lein new app mljar`
add [functionalbytes/mount-lite "0.9.5"]  to project.clj
change src/mljar/core.clj to
```
(ns mljar.core
  (:require
   [mount.lite :as mount :refer (defstate)])
  (:gen-class))


(defstate a
  :start (do
           (println "Started")
           10)
  :stop (println "Stoped"))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!")
  (mount/start)
  (println "A = " a)
  (mount/stop))
```
`lein run` output:
> Hello, World!
> Started
> A =  10
> Stoped

`lein uberjar`
> Created /tmp/mljar/target/uberjar/mljar-0.1.0-SNAPSHOT-standalone.jar

`java -jar /tmp/mljar/target/uberjar/mljar-0.1.0-SNAPSHOT-standalone.jar`

> Hello, World!
> A =  #object[clojure.lang.Var$Unbound 0x53f3bdbd Unbound: #'mljar.core/a]

**Comment by aroemers** [comment]
Hi @aksenov, thanks for the steps to reproduce the issue you are having. I am glad I can tell you that the just released version `0.9.7` will fixes the issue for above steps. If it does for you as well, happy coding! If not, please reopen this issue.

**Comment by aksenov** [comment]
Yep, it all works for now. Thanks.

**Comment by aroemers** [comment]
Great, and thanks for reporting back.
